f=open("xyz.txt","w")
print(type(f))
print(f.name)
print(f.mode)
print("is file readable:",f.readable())
print("is file writable:",f.writable())
print("is file closed:",f.closed)
f.close()
print("is file closed:",f.closed)